Added try catch to handle Attribute Error in Python 3
Python 3 doesn't support str.decode method. 
So, trying to decode access_token in python 3 raises following error:
AttributeError: 'str' object has no attribute 'decode'

Added try except block to prevent that.