update _default_jwt_payload_handler
made changes to cater for when the instance of the return identity is a dictionary. 
the current code returns the following error
```    identity = getattr(identity, 'id') or identity['id']
AttributeError: 'dict' object has no attribute 'id'
```